### ISSUE TITLE
Application crash. GetLoadForList OverflowException

### ISSUE THREAD

**Issue by will-quast** [AirVPN/Eddie#102]
Eddie was running and connected for several days then was found that the UI had unexpectedly disappeared.  
Unknown steps to reproduce.

```
Application: Eddie-UI.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.OverflowException
   at System.Convert.ToInt16(Int32)
   at Eddie.Core.ConnectionInfo.GetLoadForList()
   at Eddie.Core.Engine.OnRefreshUi(RefreshUiMode)
   at Eddie.Forms.Engine.OnRefreshUi(RefreshUiMode)
   at Eddie.Core.Engine.PostManifestUpdate()
   at Eddie.Core.ProvidersManager.Refresh()
   at Eddie.Core.Threads.Manifest.OnRun()
   at Eddie.Core.Thread.DoRun()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

Eddie version: 2.16.3
Eddie OS build: windows_x64
Eddie architecture: x64
OS type: Windows
OS name: Windows 10 Home
OS version: Microsoft Windows NT 10.0.18363.0
OS architecture: x64
Mono /.Net Framework: v4.0.30319
OpenVPN driver: TAP-Windows Adapter V9, version 9.21.2
OpenVPN: 2.4.6 - OpenSSL 1.1.0h  27 Mar 2018, LZO 2.10

**Comment by AirVPN** [comment]
Resolved for everyone (with a server-side fix, don't need to update Eddie).
