### ISSUE TITLE
[Raspberry Pi] - unable to start Eddie UI

### ISSUE THREAD

**Issue by stevenhurwitt** [AirVPN/Eddie#109]
Hi,

Thanks for the work on this - I really enjoy using it! Trying to set it up on my Raspberry Pi and it's crashing when I start the GUI. I installed with the ubuntu package manager using `sudo apt install eddie-ui`, but when I run `eddie-ui --clie` this is the stack trace I get:

```
=================================================================
	Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	 (No frames) 


=================================================================
	Telemetry Dumper:
=================================================================
Pkilling 0xb47a6460 from 0xb6f4c010
Entering thread summarizer pause from 0xb6f4c010
Finished thread summarizer pause from 0xb6f4c010.

Waiting for dumping threads to resume

=================================================================
	External Debugger Dump:
=================================================================
[New LWP 11759]
[New LWP 11760]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
__libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:46
46	../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S: No such file or directory.
  Id   Target Id                                   Frame 
* 1    Thread 0xb6f4c010 (LWP 11757) "mono"        __libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:46
  2    Thread 0xb63ff460 (LWP 11759) "SGen worker" __libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:46
  3    Thread 0xb47a6460 (LWP 11760) "Finalizer"   __libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:46

Thread 3 (Thread 0xb47a6460 (LWP 11760)):
#0  __libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:46
#1  0xb6e695f6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, clockid=0, expected=1, futex_word=0x784378) at ../sysdeps/nptl/futex-internal.h:320
#2  do_futex_wait (sem=sem@entry=0x784378, abstime=0x0, clockid=0) at sem_waitcommon.c:117
#3  0xb6e696e4 in __new_sem_wait_slow (sem=0x784378, abstime=0x0, clockid=0) at sem_waitcommon.c:285
#4  0x0063e212 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 2 (Thread 0xb63ff460 (LWP 11759)):
#0  __libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:46
#1  0xb6e6716e in futex_wait_cancelable (private=0, expected=0, futex_word=0x78c0b0) at ../sysdeps/nptl/futex-internal.h:183
#2  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x78c04c, cond=0x78c088) at pthread_cond_wait.c:508
#3  __pthread_cond_wait (cond=0x78c088, mutex=0x78c04c) at pthread_cond_wait.c:638
#4  0x00682270 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 1 (Thread 0xb6f4c010 (LWP 11757)):
#0  __libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:46
#1  0xb6dae93c in __GI___wait4 (usage=0x0, options=0, stat_loc=0xbe9f52d8, pid=11800) at ../sysdeps/unix/sysv/linux/wait4.c:27
#2  __GI___wait4 (pid=11800, stat_loc=0xbe9f52d8, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:24
#3  0x004dc862 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
[Inferior 1 (process 11757) detached]

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0xb6e67d20):0xb6e67d10  00 01 30 bc 70 47 00 bf 2d e9 f0 4f 87 b0 00 bf  ..0.pG..-..O....
0xb6e67d20  45 6a eb 08 00 f0 9a 81 15 f0 01 05 06 46 56 f8  Ej...........FV.
0xb6e67d30  20 3f 04 46 18 bf 80 25 0e e0 43 f0 01 01 56 e8   ?.F...%..C...V.
0xb6e67d40  00 2f 9a 42 05 d1 46 e8 00 10 00 28 f7 d1 bf f3  ./.B..F....(....

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at Eddie.Forms.Linux.Program:Main <0x00013>
	  at System.Object:runtime_invoke_void <0x000e3>
=================================================================
/usr/bin/eddie-ui: line 2: 11757 Aborted                 (core dumped) mono /usr/lib/eddie-ui/eddie-ui.exe --path.resources=/usr/share/eddie-ui --path.exec="$0" "$@"
```

Any advice or help is appreciated!

**Comment by AirVPN** [comment]
Sorry to hear that.
What distro exactly? An Ubuntu, i understand.
Currently we build/test Raspbian and Raspbian 64bit, we forward this issue to our labs for investigation.

**Comment by stevenhurwitt** [comment]
hey, i think it was raspbian 64bit!

**Comment by AirVPN** [comment]
Please retry the latest 2.20.0 release, we fixed a bug about arm64 (not sure if is related to your crash, but maybe).
Waiting for feedback, thx.

**Comment by stevenhurwitt** [comment]
shoot i've actually changed my raspberry pi's to use ubuntu 20.04 since i was running into stability issues with raspbian. so i am unable to test :(
